//
//  module.cpp
//  xlua / xTLua module runtime
//
//  Created by Ben Supnik on 3/19/16.
//
//  XTLua
//  Modified by Mark Parker on 04/19/2020
//  Hardened / commented by Peter Schwake on 26/08/2026
//  Runtime naming/comments updated for xtlua_worker/xtlua_main/xlua2_main on 21/09/2026
//
//	Copyright 2016, Laminar Research
//	This source code is licensed under the MIT open source license.
//	See LICENSE.txt for the full terms of the license.
//
//------------------------------------------------------------------------------
//  ZWECK
//    Kapselt EINEN Lua-Interpreter ("module") samt zugehoerigem Skript-Paar
//    (init-Script + Modul-Script) und einem eigenen Bump-Allocator fuer
//    Speicher, der an die Lebensdauer des Moduls gebunden ist.
//
//    Ein module-Objekt kann in drei klar getrennten Laufzeitmodi arbeiten:
//      - xtlua_worker : asynchroner XTLua-Worker; before_physics() und
//                       after_physics() laufen unabhaengig vom X-Plane-Thread.
//      - xtlua_main   : XTLua-Main-Thread-Begleitpfad fuer direkte XLua-kompatible Bindings.
//      - xlua2_main   : XLua-2-/SDK-4.4-Pfad mit direkten XPLM-Bindings.
//
//  THREADING-VERTRAG
//    Der asynchrone xtlua_worker ist der Kern von XTLua. Dieser Runtime-Pfad
//    darf keine direkten XPLM-Simulatorzugriffe aus Lua heraus erhalten;
//    Simulatorzustand und Aktionen muessen ueber die gepufferten XTLua-
//    Schnittstellen zwischen Worker und X-Plane-Thread ausgetauscht werden.
//
//    xtlua_main und xlua2_main laufen dagegen auf dem X-Plane-Thread.
//    xlua2_main darf deshalb die generierten direkten XPLM-Bindings verwenden.
//
//    Auch module_log() und log_message() uebergeben ausschliesslich eigene
//    Textkopien an die Logqueue. Nur deren Main-Thread-Drain schreibt per
//    XPLMDebugString(); dabei ist kein Worker-/Logqueue-Lock gehalten.
//
//  HISTORISCHE HARDENING-FIXES (Details jeweils am Fundort als "// FIX Mx:")
//    M1  make_alloc_block: Heap-Overflow (zu kleines malloc)
//    M2  alloc_from_block: Alignment / Uebergroessen / NULL-Handling
//    M3  CTOR_FAIL: UB bei leerem Lua-Stack bzw. nicht-String-Fehler
//    M4  Konstruktor: NULL-Parameter, uninitialisiertes m_debug_proc
//    M5  Chunkname-Offset wurde vom falschen Pfad uebernommen
//    M6  run_module_in_namespace ungeprueft aufgerufen
//    M7  alle printf entfernt
//    M8  xmap_class: Datei-I/O-Fehler wurden ignoriert
//    M9  load_module_relative_path ohne Interpreter
//    M10 do_callout: Typpruefung des Callouts
//    M11 Destruktor: Zeiger nullen
//    M12 unerreichbarer Code entfernt
//------------------------------------------------------------------------------

#include "module.h"
#include "xpfuncs.h"
#include "lua_helpers.h"
#include "shared_xpfuncs.h"
#include "xlua_command_bindings.h"
#include "xlua2_host.h"
#include "xtlua2_imgui.h"
#include "xtlua_render_bridge.h"

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stdarg.h>
#include <stddef.h>      // offsetof
#include <assert.h>
#include <chrono>
#include <cstdint>
#include <math.h>
#include <algorithm>
#include <regex>
#include <utility>

// Generated by SDK/XLua_glue/XLua_Register_glue.cpp.
void add_xplm_to_interp(lua_State * L);

// Private Lua-registry key for the owning module. Unlike a named Lua global,
// the address cannot be replaced accidentally by aircraft code.
static char s_module_registry_key;

//==============================================================================
// 0. LOGGING
//------------------------------------------------------------------------------
// FIX M7: Es gibt in dieser Datei keine direkten printf-Aufrufe fuer
// Modulfehler oder Modul-Trace mehr.
//   - Fehler laufen ueber module_log() -> Logqueue -> Main-Thread (Log.txt).
//   - Reine Fortschrittsmeldungen sind hinter XTLUA_MODULE_TRACE versteckt und
//     per Default AUS, weil sie beim Laden vieler Module das Log zumuellen.
//
// Threading-Hinweis: Alle Runtimes verwenden dieselbe FIFO-Textqueue.
// Weder der Worker noch die Logger in dieser Datei rufen XPLM direkt auf.
// Beides laesst sich beim Build ueberschreiben (-DXTLUA_MODULE_LOG=0 usw.).
//==============================================================================

#ifndef XTLUA_MODULE_LOG
	#define XTLUA_MODULE_LOG 1      // Fehlermeldungen: an
#endif
#ifndef XTLUA_MODULE_TRACE
	#define XTLUA_MODULE_TRACE 0    // Fortschrittsmeldungen: aus
#endif

#if XTLUA_MODULE_LOG
#if defined(__GNUC__) || defined(__clang__)
	#define XTLUA_PRINTFLIKE __attribute__((format(printf,1,2)))
#else
	#define XTLUA_PRINTFLIKE
#endif

static void module_log(const char * fmt, ...) XTLUA_PRINTFLIKE;
static void module_log(const char * fmt, ...)
{
	char buf[1024];
	va_list va;
	va_start(va, fmt);
	// snprintf-Familie: kuerzt notfalls ab, statt den Puffer zu ueberschreiben.
	vsnprintf(buf, sizeof(buf), fmt, va);
	va_end(va);
	buf[sizeof(buf) - 1] = 0;
	xtlua_queue_log(buf);
}
#else
static void module_log(const char *, ...) { }
#endif

#if XTLUA_MODULE_TRACE
	#define MODULE_TRACE(...) module_log(__VA_ARGS__)
#else
	#define MODULE_TRACE(...) ((void) 0)
#endif

//==============================================================================
// 1. PFAD-HELFER
//==============================================================================

// Liefert den Zeiger auf den Dateinamen innerhalb eines Pfades
// ("a/b/c.lua" -> "c.lua"). NULL-sicher.
static const char * shorten_to_file(const char * path)
{
	if(path == NULL)
		return "";

	const char * p = path, * t = path;
	while(*p)
	{
		if(*p == '/' || *p == '\\')
			t = p + 1;
		++p;
	}
	return t;
}

// Laenge des Verzeichnisanteils (inkl. abschliessendem Separator).
static ptrdiff_t length_of_dir(const char * p)
{
	if(p == NULL)
		return 0;

	const char * f = shorten_to_file(p);
	return f - p;
}

// FIX M5: In der urspruenglichen Implementierung wurde 'boiler_plate_paths' aus in_init_script berechnet
// und dann blind auf in_module_script addiert. Liegt das Modul-Skript in einem
// kuerzeren Pfad als das init-Skript, zeigt 'path + dir_len' HINTER das
// Stringende -> Lua liest fremden Speicher als Chunknamen.
// Hier wird der Offset nur benutzt, wenn er in den String passt; ansonsten
// fallen wir auf den reinen Dateinamen zurueck.
static const char * chunk_name_for(const char * path, ptrdiff_t dir_len)
{
	if(path == NULL)
		return "?";

	size_t len = strlen(path);
	if(dir_len <= 0 || (size_t) dir_len > len)
		return shorten_to_file(path);

	return path + dir_len;
}

// FIX M3: lua_tostring kann NULL liefern (Nicht-String-Fehlerobjekt), und bei
// leerem Stack ist der Zugriff auf Index -1 undefiniert. Beides wird hier
// abgefangen, damit die Fehlermeldung selbst nicht zum Crash fuehrt.
static const char * safe_lua_error(lua_State * L)
{
	if(L == NULL)
		return "(no interpreter)";
	if(lua_gettop(L) == 0)
		return "(no error message on stack)";

	const char * s = lua_tostring(L, -1);
	return s ? s : "(non-string error object)";
}

static int xlua2_dofile(lua_State * L)
{
	module * owner = module::module_from_interp(L);
	if(owner == NULL || !owner->is_xlua2())
		return luaL_error(L, "XLua 2 module context unavailable");

	const char * relative_path = luaL_checkstring(L, 1);
	lua_settop(L, 1);
	const int load_result = owner->load_module_relative_path(relative_path);
	if(load_result != 0)
		return lua_error(L);

	// Remove the path argument, execute the loaded chunk, and preserve all
	// return values just like Lua's standard dofile().
	lua_remove(L, 1);
	lua_call(L, 0, LUA_MULTRET);
	return lua_gettop(L);
}

// Keep the complete original closure: generated bindings may acquire upvalues
// in a later SDK. A raw function-pointer call would silently lose that context.
static int xlua2_binding_dispatch(lua_State * L)
{
	module * owner = module::module_from_interp(L);
	if(owner == NULL || !owner->is_xlua2() || owner->is_closing())
		return luaL_error(L, "XLua 2 bindings unavailable while module is closing");
	const int argument_count = lua_gettop(L);
	lua_pushvalue(L, lua_upvalueindex(1));
	lua_insert(L, 1);
	// Protect the depth counter from Lua longjmp; SDK enumeration callbacks
	// must work even in top-level code or XPluginStart/XPluginEnable.
	owner->enter_sdk_call();
	const int result = lua_pcall(L, argument_count, LUA_MULTRET, 0);
	owner->leave_sdk_call();
	if(result != 0)
		return lua_error(L);
	return lua_gettop(L);
}

static void guard_xlua2_bindings(lua_State * L)
{
	// Run once, before aircraft code can retain unguarded SDK function aliases.
	// Only replace existing values, never mutate the key set while traversing.
	lua_pushnil(L);
	while(lua_next(L, LUA_GLOBALSINDEX) != 0)
	{
		if(lua_type(L, -2) == LUA_TSTRING && lua_iscfunction(L, -1))
		{
			const char * name = lua_tostring(L, -2);
			if(strncmp(name, "XPLM", 4) == 0 || strncmp(name, "XLua", 4) == 0)
			{
				lua_pushvalue(L, -2);
				lua_pushvalue(L, -2);
				lua_pushcclosure(L, xlua2_binding_dispatch, 1);
				lua_rawset(L, LUA_GLOBALSINDEX);
			}
		}
		lua_pop(L, 1);
	}
}

static int module_print(lua_State * L)
{
	// Use Lua's tostring contract (including __tostring) before owning C++
	// strings, so a Lua error cannot skip their destructors through longjmp.
	const int argument_count = lua_gettop(L);
	luaL_Buffer buffer;
	luaL_buffinit(L, &buffer);
	for(int i = 1; i <= argument_count; ++i)
	{
		if(i > 1)
			luaL_addchar(&buffer, '\t');
		lua_getglobal(L, "tostring");
		lua_pushvalue(L, i);
		lua_call(L, 1, 1);
		size_t length = 0;
		const char * value = lua_tolstring(L, -1, &length);
		if(value == NULL)
			return luaL_error(L, "tostring must return a string for print");
		luaL_addvalue(&buffer); // consumes the value, including buffer flushes
	}
	luaL_pushresult(&buffer);
	size_t length = 0;
	const char * output = lua_tolstring(L, -1, &length);
	module * owner = module::module_from_interp(L);
	string log_line("XTLua: ");
	if(owner != NULL)
	{
		switch(owner->get_runtime())
		{
		case module_runtime::xtlua_worker: log_line += "xtlua_worker: "; break;
		case module_runtime::xtlua_main: log_line += "xtlua_main: "; break;
		case module_runtime::xlua2_main: log_line += "xlua2_main: "; break;
		}
		log_line += owner->get_script_path();
		log_line += ": ";
	}
	log_line.append(output, length);
	log_line += '\n';
	xtlua_queue_log(std::move(log_line));
	return 0;
}

//==============================================================================
// 2. DATEI-MAPPING
//------------------------------------------------------------------------------
// HINWEIS (unveraendert aus dem Original): xmap_class ist nur fuer !MOBILE
// definiert, wird im Konstruktor aber unbedingt benutzt. Fuer MOBILE-Builds
// muesste hier eine Bundle-/Speicher-Variante ergaenzt werden - das ist eine
// Design-Entscheidung und bleibt daher unangetastet.
//==============================================================================

#if !MOBILE

class	xmap_class {
public:
	xmap_class(const string& in_file_name);
	~xmap_class() { free(m_buffer); m_buffer = NULL; m_size = 0; }

	bool exists() const { return m_buffer != NULL; } // Includes valid empty chunks.
	const char * begin() const { return m_buffer; }
	size_t size() const { return m_size; }

private:
	// Kein Kopieren: sonst wuerde m_buffer doppelt freigegeben.
	xmap_class(const xmap_class&);
	xmap_class& operator=(const xmap_class&);

	char *		m_buffer;
	size_t		m_size;
};

#endif

//==============================================================================
// 3. BUMP-ALLOCATOR
//------------------------------------------------------------------------------
// Sehr einfacher "Arena"-Allocator: Bloecke werden verkettet, innerhalb eines
// Blocks wird nur ein Zeiger hochgeschoben. Einzelfreigaben gibt es nicht -
// alles stirbt gemeinsam im Destruktor (destroy_alloc_block).
//==============================================================================

#define MALLOC_CHUNK_SIZE 4096   // Nutzlast pro Standardblock (NICHT Gesamtgroesse!)

struct module_alloc_block {
	module_alloc_block *	next;
	char *					ptr;		// naechste freie Adresse in data[]
	size_t					remaining;	// noch freie Bytes ab ptr
	char					data[MALLOC_CHUNK_SIZE];
};

// Alignment fuer alle Rueckgaben. data[] folgt auf drei zeigergrosse Felder,
// ist also mindestens sizeof(void*)-aligned; mehr koennen wir ohne
// alignas/Padding nicht garantieren. Fuer double/int64 ist das auf allen von
// X-Plane unterstuetzten Plattformen ausreichend.
static const size_t kAllocAlign = sizeof(void *);

// FIX M1: Die urspruengliche Implementierung rief malloc(MALLOC_CHUNK_SIZE) fuer eine Struktur auf,
// die MALLOC_CHUNK_SIZE + Header gross ist, und setzte remaining anschliessend
// auf die vollen MALLOC_CHUNK_SIZE. Jeder Block hat also ueber sein Ende hinaus
// geschrieben (Heap-Corruption, typischerweise als Absturz an ganz anderer
// Stelle sichtbar). Jetzt wird korrekt Header + Nutzlast reserviert.
// Ausserdem: assert(r) hilft im Release-Build nicht -> echter NULL-Pfad.
static module_alloc_block * make_alloc_block(size_t payload)
{
	if(payload < MALLOC_CHUNK_SIZE)
		payload = MALLOC_CHUNK_SIZE;

	// Overflow-Schutz fuer die Additions-Rechnung.
	const size_t hdr = offsetof(module_alloc_block, data);
	if(payload > (size_t) -1 - hdr)
		return NULL;

	module_alloc_block * r = (module_alloc_block *) malloc(hdr + payload);
	if(r == NULL)
	{
		module_log("xtlua: module allocator out of memory (%zu bytes)\n",
				   hdr + payload);
		return NULL;
	}

	r->next = NULL;
	r->ptr = r->data;
	r->remaining = payload;
	return r;
}

// FIX M2:
//   a) 'assert(amt <= MALLOC_CHUNK_SIZE)' war im Release wirkungslos -> eine
//      grosse Anfrage hat den Block ueberschrieben. Uebergrosse Anfragen
//      bekommen nun einen eigenen, passend dimensionierten Block.
//   b) Keine Alignment-Rundung: nach einer 3-Byte-Anfrage war jede folgende
//      Adresse schief (auf ARM/32-Bit real problematisch).
//   c) Ein fehlgeschlagenes make_alloc_block wurde ungeprueft dereferenziert.
//   d) amt == 0 gab zweimal dieselbe Adresse zurueck.
static void * alloc_from_block(module_alloc_block *& head, size_t amt)
{
	if(amt == 0)
		amt = 1;

	// auf kAllocAlign aufrunden, overflow-sicher
	if(amt > (size_t) -1 - (kAllocAlign - 1))
		return NULL;
	amt = (amt + (kAllocAlign - 1)) & ~(kAllocAlign - 1);

	// Schnellpfad: passt in den aktuellen Block.
	if(head != NULL && head->remaining >= amt)
	{
		void * r = head->ptr;
		head->ptr += amt;
		head->remaining -= amt;
		return r;
	}

	module_alloc_block * nb = make_alloc_block(amt);
	if(nb == NULL)
		return NULL;					// Aufrufer MUSS auf NULL pruefen

	void * r = nb->ptr;
	nb->ptr += amt;
	nb->remaining -= amt;

	if(head == NULL)
	{
		head = nb;
	}
	else if(amt > MALLOC_CHUNK_SIZE)
	{
		// Sonderblock ist bereits voll ausgereizt -> hinter head einhaengen,
		// damit der Restplatz im aktuellen head weiter nutzbar bleibt.
		nb->next = head->next;
		head->next = nb;
	}
	else
	{
		nb->next = head;
		head = nb;					// neuer Block wird aktiver Block
	}

	return r;
}

static void destroy_alloc_block(module_alloc_block * head)
{
	while(head)
	{
		module_alloc_block * k = head;
		head = head->next;
		free(k);
	}
}

//==============================================================================
// 4. KONSTRUKTOR / DESTRUKTOR
//==============================================================================

// FIX M3/M7: Kein printf mehr, kein Zugriff auf einen moeglicherweise leeren
// Lua-Stack, und lua_close wird nur bei gueltigem State aufgerufen.
// Wichtig: Das Makro fuehrt ein 'return' aus - der Aufrufer erkennt das
// Scheitern daran, dass m_interp == NULL ist (so wie im Original).
#define CTOR_FAIL(errcode,msg)                                              \
	if((errcode) != 0) {                                                    \
		module_log("xtlua: %s failed (%d): %s\n",                           \
				   (msg), (int)(errcode), safe_lua_error(m_interp));         \
		shutdown_lua();                                                       \
		return; }

module::module(
							const char *		in_module_path,
							const char *		in_init_script,
							const char *		in_module_script,
							module_runtime		in_runtime) :
	m_interp(nullptr)         // zuerst m_interp (wie in module.h)
  , m_memory(nullptr)         // dann m_memory
  , m_path(in_module_path ? in_module_path : "")
  , m_script_path(in_module_script ? in_module_script : "")
  , m_debug_proc(0)
  , m_runtime(in_runtime)
  , m_started(false)
  , m_enabled(false)
  , m_closing(false)
{
	// ---- Parameter validieren -------------------------------------------------
	// FIX M4: Alle drei Pfade wurden ungeprueft dereferenziert
	// (length_of_dir, luaL_loadbuffer-Chunkname, fopen).
	if(in_module_path == NULL || in_init_script == NULL || in_module_script == NULL)
	{
		module_log("xtlua: module ctor called with NULL path "
				   "(module=%s init=%s script=%s)\n",
				   in_module_path   ? in_module_path   : "(null)",
				   in_init_script   ? in_init_script   : "(null)",
				   in_module_script ? in_module_script : "(null)");
		return;						// m_interp bleibt NULL -> Modul ist "leer"
	}

	// Offset, ab dem Pfade im Log/Chunknamen gekuerzt werden (nur Kosmetik).
	const ptrdiff_t boiler_plate_paths = length_of_dir(in_init_script);
	const char *    init_chunk   = chunk_name_for(in_init_script,   boiler_plate_paths);
	const char *    module_chunk = chunk_name_for(in_module_script, boiler_plate_paths);

	// FIX M7: Runtime-spezifisches Start-Trace statt ungefiltertem printf.
	if(m_runtime == module_runtime::xtlua_worker)
		MODULE_TRACE("xtlua_worker: running module %s\n", module_chunk);
	else if(m_runtime == module_runtime::xtlua_main)
		MODULE_TRACE("xtlua_main: running module %s\n", module_chunk);
	else if(m_runtime == module_runtime::xlua2_main)
		MODULE_TRACE("xlua2_main: running module %s\n", module_chunk);

	// ---- Lua-State aufsetzen -------------------------------------------------
	m_interp = luaL_newstate();
	if(m_interp == NULL)
	{
		module_log("xtlua: unable to set up Lua for %s\n", module_chunk);
		return;
	}
	if(m_runtime == module_runtime::xlua2_main)
		xlua_install_panic_handler(m_interp);
	luaL_openlibs(m_interp);
	set_stdvars_direct_sdk(
		m_interp,
		m_runtime == module_runtime::xlua2_main);

	// Rueckzeiger, damit module_from_interp() aus jedem Lua-Callback heraus
	// wieder an dieses Objekt kommt. Der Registry-Eintrag ist autoritativ;
	// __module_ptr bleibt nur fuer bestehende Skripte/Tools als Kompatibilitaet.
	lua_pushlightuserdata(m_interp, &s_module_registry_key);
	lua_pushlightuserdata(m_interp, this);
	lua_rawset(m_interp, LUA_REGISTRYINDEX);
	lua_pushlightuserdata(m_interp, this);
	lua_setglobal(m_interp, "__module_ptr");

	if(m_runtime == module_runtime::xlua2_main)
	{
		lua_pushinteger(m_interp, 2);
		lua_setglobal(m_interp, "XLuaMajorVersion");
		lua_pushstring(m_interp, "2.0.0a1-xtlua");
		lua_setglobal(m_interp, "XLuaPluginVersion");
		add_xplm_to_interp(m_interp);
		guard_xlua2_bindings(m_interp);
		LoadImguiBindings(m_interp);
		xtlua2_imgui_register_text_inputs(m_interp);
		lua_register(m_interp, "dofile", xlua2_dofile);

		// Keep Lua's built-in package search path and add the generated SDK
		// metadata modules next to the aircraft plugin.
		lua_getglobal(m_interp, "package");
		lua_getfield(m_interp, -1, "path");
		const char * current_path = lua_tostring(m_interp, -1);
		string package_path = current_path ? current_path : "";
		lua_pop(m_interp, 1);
		if(!package_path.empty() && package_path.back() != ';')
			package_path += ';';
		string include_path = m_path + "../../include/?.lua";
		std::replace(include_path.begin(), include_path.end(), '\\', '/');
		package_path += include_path;
		lua_pushstring(m_interp, package_path.c_str());
		lua_setfield(m_interp, -2, "path");
		lua_pop(m_interp, 1);
	}
	else
	{
		// xtlua_worker erhaelt die gepufferten/asynchronen XTLua-Bindings.
		// xtlua_main erhaelt den direkten XLua-kompatiblen Main-Thread-Satz.
		add_xpfuncs_to_interp(
			m_interp,
			m_runtime == module_runtime::xtlua_worker);
	}
	xtlua_register_render_bridge(m_interp, m_runtime);
	lua_register(m_interp, "print", module_print);

	// ---- init-Skript laden und ausfuehren -----------------------------------
	// Mobile devices like Android don't use a regular file system... they have a
	// bundle of resources in-memory, so we load Lua from a memory buffer.
	xmap_class linit(in_init_script);
	if(!linit.exists())
	{
		// Hinweis: Hier liegt KEINE Lua-Fehlermeldung auf dem Stack - genau der
		// Fall, der in der urspruenglichen Implementierung zu UB in lua_tostring fuehrte.
		module_log("xtlua: cannot read init script '%s'\n", in_init_script);
		shutdown_lua();
		return;
	}

	// Traceback-Funktion auf den Stack; ihr Index dient allen pcalls als
	// Errorhandler und muss fuer die Lebensdauer des States dort liegen bleiben.
	m_debug_proc = lua_pushtraceback(m_interp);
	if(m_runtime == module_runtime::xlua2_main)
	{
		int * debug_proc = static_cast<int *>(lua_newuserdata(m_interp, sizeof(int)));
		*debug_proc = m_debug_proc;
		lua_setglobal(m_interp, "__debug_proc");
	}

	int load_result = luaL_loadbuffer(m_interp,
									  (const char *) linit.begin(),
									  linit.size(),
									  init_chunk);
	CTOR_FAIL(load_result, "load init script")

	int init_script_result = lua_pcall(m_interp, 0, 0, m_debug_proc);
	CTOR_FAIL(init_script_result, "run init script");

	// xtlua_worker und xtlua_main behalten den privaten XLua-Namespace.
	// xlua2_main fuehrt das Modul dagegen direkt in der globalen State-Tabelle
	// aus und entspricht damit dem oeffentlichen XLua-2-Vertrag.
	if(m_runtime != module_runtime::xlua2_main)
	{
		lua_getfield(m_interp, LUA_GLOBALSINDEX, "run_module_in_namespace");
		if(!lua_isfunction(m_interp, -1))
		{
			module_log("xtlua: init script '%s' did not define "
					   "run_module_in_namespace()\n", init_chunk);
			shutdown_lua();
			return;
		}
	}

	xmap_class lmod(in_module_script);
	if(!lmod.exists())
	{
		module_log("xtlua: cannot read module script '%s'\n", in_module_script);
		shutdown_lua();
		return;
	}

	// Fuer xtlua_worker und xtlua_main ist der Chunk das Argument fuer
	// run_module_in_namespace(). Bei xlua2_main wird der Chunk direkt ausgefuehrt.
	int module_load_result = luaL_loadbuffer(m_interp,
											(const char *) lmod.begin(),
											lmod.size(),
											module_chunk);
	CTOR_FAIL(module_load_result, "load module");

	int module_run_result = lua_pcall(
		m_interp,
		m_runtime == module_runtime::xlua2_main ? 0 : 1,
		0,
		m_debug_proc);
	CTOR_FAIL(module_run_result, "run module");
}

module::~module()
{
	// FIX M11: Zeiger nach der Freigabe nullen - schuetzt gegen versehentliche
	// Doppelfreigabe und macht Use-after-free im Debugger sichtbar.
	shutdown_lua();
	destroy_alloc_block(m_memory);
	m_memory = NULL;
}

void module::prepare_shutdown()
{
	m_closing = true;
}

void module::shutdown_lua()
{
	if(m_interp == NULL)
		return;

	if(m_runtime == module_runtime::xlua2_main)
	{
		xplugin_disable();
		xplugin_stop();
		// Hooks above may clean up normally. From here no callback/finalizer
		// may create new SDK work while captures and resource lists are retired.
		prepare_shutdown();
		xtlua2_imgui_cleanup_state(m_interp);

		// XPLM must no longer hold command/timer callback refcons when the
		// corresponding Lua registry and callback captures are released.
		xlua_command_bindings_cleanup(m_interp);
		xlua_remove_timers_for_state(m_interp);
		xlua_callback_cleanup(m_interp);
	}

	// XLua 2 shutdown hooks above must retain their normal SDK access. Classic
	// modules may already have been marked closing by the host before it retires
	// handles; construction-failure teardown reaches this gate directly instead.
	prepare_shutdown();
	lua_close(m_interp);
	m_interp = NULL;
}

//==============================================================================
// 5. SKRIPT-NACHLADEN
//==============================================================================

int module::load_module_relative_path(const string& path)
{
	// FIX M9: luaL_error() mit NULL-State war ein sicherer Crash. Kann eintreten,
	// wenn der Konstruktor gescheitert ist und das Objekt trotzdem benutzt wird.
	if(m_interp == NULL)
		return -1;

	string script_path = m_path + path;

	xmap_class script_text(script_path);
	if(!script_text.exists())
	{
		// luaL_error() macht ein longjmp innerhalb des Lua-Aufrufs -
		// Return a status instead: the caller raises after our locals unwind.
		lua_pushfstring(m_interp, "Unable to load script file: %s", path.c_str());
		return LUA_ERRFILE;
	}

	return luaL_loadbuffer(m_interp,
						   (const char *) script_text.begin(),
						   script_text.size(),
						   path.c_str());
}

//==============================================================================
// 6. LUA <-> C++ BRUECKE
//==============================================================================

int module::debug_proc_from_interp(lua_State * interp)
{
	module * me = module_from_interp(interp);
	if(me)
		return me->m_debug_proc;
	return 0;
}

module * module::module_from_interp(lua_State * interp)
{
	if(interp == NULL)
		return NULL;

	lua_pushlightuserdata(interp, &s_module_registry_key);
	lua_rawget(interp, LUA_REGISTRYINDEX);

	if(lua_islightuserdata(interp, -1))
	{
		module * me = (module *) lua_touserdata(interp, -1);
		lua_pop(interp, 1);
		return me;
	}
	else
	{
		lua_pop(interp, 1);
		return NULL;
	}
}

void * module::module_alloc_tracked(size_t amount)
{
	// Rueckgabe kann jetzt NULL sein (OOM oder absurde Groesse) - Aufrufer
	// sollten das pruefen. Vorher war ein NULL hier ein sicherer Crash im
	// Allocator selbst.
	return alloc_from_block(m_memory, amount);
}

//==============================================================================
// 7. RUNTIME-CALLOUTS
//------------------------------------------------------------------------------
// xtlua_worker: Aufruf aus dem asynchronen Worker-Zyklus.
// xtlua_main   : Aufruf auf dem X-Plane-Main-Thread.
// xlua2_main  : direkter Funktionsaufruf im XLua-2-State auf dem Main Thread.
//==============================================================================

void	module::acf_load()      { do_callout("aircraft_load");   }
void	module::acf_unload()    { do_callout("aircraft_unload"); }
void	module::flight_init()   { do_callout("flight_start");    }
void	module::flight_crash()  { do_callout("flight_crash");    }
void	module::post_replay()   { do_callout("after_replay");    }

int		module::pre_physics()   { return do_callout("before_physics"); }

// FIX M12: In der urspruenglichen Implementierung stand hinter dem 'return' ein auskommentierter
// Timing-Block, dessen Code ohnehin unerreichbar gewesen waere. Wer das Timing
// braucht, muss es VOR das return ziehen (Messung dann um den do_callout legen).
int		module::post_physics()  { return do_callout("after_physics"); }

int module::do_callout(const char * f)
{
	if(m_interp == NULL || f == NULL)
		return 0;
	if(m_runtime == module_runtime::xlua2_main)
	{
		if(!m_enabled)
			return 0;
		return do_direct_callout(f);
	}

	lua_getfield(m_interp, LUA_GLOBALSINDEX, "do_callout");

	// FIX M10: Nur auf nil zu pruefen genuegt nicht - jeder andere
	// Nicht-Funktions-Wert wuerde erst im pcall als Fehler auflaufen.
	if(!lua_isfunction(m_interp, -1))
	{
		lua_pop(m_interp, 1);
		return 0;
	}

	// fmt_pcall_stdvars konsumiert die Funktion vom Stack und ruft sie mit
	// dem Callout-Namen als String-Argument auf.
	return fmt_pcall_stdvars(m_interp, m_debug_proc, false, "s", f);
}

int module::do_direct_callout(const char * f)
{
	if(m_interp == NULL || f == NULL)
		return 0;

	lua_getfield(m_interp, LUA_GLOBALSINDEX, f);
	if(!lua_isfunction(m_interp, -1))
	{
		lua_pop(m_interp, 1);
		return 0;
	}
	return fmt_pcall_stdvars(m_interp, m_debug_proc, false, "");
}

bool module::xplugin_start()
{
	if(m_runtime != module_runtime::xlua2_main || m_interp == NULL)
		return false;
	if(m_started)
		return true;

	lua_getfield(m_interp, LUA_GLOBALSINDEX, "XPluginStart");
	if(!lua_isfunction(m_interp, -1))
	{
		lua_pop(m_interp, 1);
		m_started = true;
		return true;
	}

	bool result = false;
	if(fmt_pcall_stdvars(m_interp, m_debug_proc, true, "") == 0)
	{
		if(lua_isboolean(m_interp, -1))
			result = lua_toboolean(m_interp, -1) != 0;
		else
			module_log("xtlua: %s XPluginStart must return a boolean\n",
				m_script_path.c_str());
		lua_pop(m_interp, 1);
	}
	m_started = result;
	return result;
}

bool module::xplugin_enable()
{
	if(m_runtime != module_runtime::xlua2_main || m_interp == NULL || !m_started)
		return false;
	if(m_enabled)
		return true;

	lua_getfield(m_interp, LUA_GLOBALSINDEX, "XPluginEnable");
	if(!lua_isfunction(m_interp, -1))
	{
		lua_pop(m_interp, 1);
		m_enabled = true;
		return true;
	}

	bool result = false;
	if(fmt_pcall_stdvars(m_interp, m_debug_proc, true, "") == 0)
	{
		if(lua_isboolean(m_interp, -1))
			result = lua_toboolean(m_interp, -1) != 0;
		else
			module_log("xtlua: %s XPluginEnable must return a boolean\n",
				m_script_path.c_str());
		lua_pop(m_interp, 1);
	}
	m_enabled = result;
	return result;
}

void module::xplugin_disable()
{
	if(m_runtime != module_runtime::xlua2_main || m_interp == NULL || !m_enabled)
		return;
	m_enabled = false;
	do_direct_callout("XPluginDisable"); // Reentrant Disable is now a no-op.
}

void module::xplugin_stop()
{
	if(m_runtime != module_runtime::xlua2_main || m_interp == NULL || !m_started)
		return;
	m_started = false;
	do_direct_callout("XPluginStop");
}

void module::xplugin_receive_message(
	int inFromWho,
	int inMessage,
	void * inParam)
{
	if(m_runtime != module_runtime::xlua2_main || m_interp == NULL || !m_enabled)
		return;

	lua_getfield(m_interp, LUA_GLOBALSINDEX, "XPluginReceiveMessage");
	if(!lua_isfunction(m_interp, -1))
	{
		lua_pop(m_interp, 1);
		return;
	}

	setup_std_vars(m_interp, m_debug_proc);
	const int debug_index = lua_gettop(m_interp);
	lua_pushtraceback(m_interp);
	lua_insert(m_interp, debug_index);
	lua_pushinteger(m_interp, inFromWho);
	lua_pushinteger(m_interp, inMessage);
	const string param_type = xlua2_event_param_type(inMessage);
	if(param_type == "*u")
	{
		if(inParam != NULL)
			lua_pushinteger(m_interp, *static_cast<const int *>(inParam));
		else
			lua_pushnil(m_interp);
	}
	else if(param_type == "i" || param_type.rfind("extdata<", 0) == 0)
	{
		lua_pushinteger(
			m_interp,
			static_cast<lua_Integer>(reinterpret_cast<intptr_t>(inParam)));
	}
	else if(inParam == NULL)
	{
		lua_pushnil(m_interp);
	}
	else
	{
		// Preserve opaque third-party pointers in the same full-userdata shape
		// accepted by the generated XPLMSendMessageToPlugin binding.
		xlua_pushuserdata<void *>(m_interp, inParam);
	}

	if(lua_pcall(m_interp, 3, 0, debug_index) != 0)
	{
		module_log("xtlua: %s XPluginReceiveMessage failed: %s\n",
			m_script_path.c_str(), safe_lua_error(m_interp));
		lua_pop(m_interp, 1);
	}
	lua_remove(m_interp, debug_index);
}

//==============================================================================
// 8. DATEI-I/O (Desktop)
//==============================================================================

#if !MOBILE

#if IBM

#include <windows.h>

//-----
// https://stackoverflow.com/questions/215963/how-do-you-properly-use-widechartomultibyte
// Convert an UTF8 string to a wide Unicode string
std::wstring utf8_decode(const std::string &str)
{
	if (str.empty()) return std::wstring();

	int size_needed = MultiByteToWideChar(CP_UTF8, 0, &str[0], (int) str.size(), NULL, 0);
	if (size_needed <= 0) return std::wstring();

	std::wstring wstrTo(size_needed, 0);
	MultiByteToWideChar(CP_UTF8, 0, &str[0], (int) str.size(), &wstrTo[0], size_needed);
	return wstrTo;
}

//-----

#endif

// FIX M8: Die urspruengliche Implementierung ignorierte I/O-Fehler:
//   - ftell() == -1 (z.B. Verzeichnis statt Datei) wurde als riesiges size_t
//     interpretiert -> malloc scheitert -> m_buffer == NULL, m_size aber gesetzt
//     -> exists() lieferte fuer NULL-Buffer bereits false, aber der
//        Rueckgabewert von malloc wurde ungeprueft an fread gegeben.
//   - eine unvollstaendige Leseoperation blieb unbemerkt -> Lua bekam
//     uninitialisierten Speicher als Skript.
// Jetzt: jeder Schritt geprueft, m_size == tatsaechlich gelesene Bytes.
xmap_class::xmap_class(const string& in_file_name) :
	m_buffer(NULL), m_size(0)
{
#if IBM
	FILE * fi = _wfopen(utf8_decode(in_file_name).c_str(), L"rb");
#else
	FILE * fi = fopen(in_file_name.c_str(), "rb");
#endif
	if(fi == NULL)
		return;

	if(fseek(fi, 0, SEEK_END) != 0)
	{
		fclose(fi);
		return;
	}

	long end = ftell(fi);
	if(end < 0)					// A zero-byte Lua file is a valid empty chunk.
	{
		fclose(fi);
		return;
	}

	if(fseek(fi, 0, SEEK_SET) != 0)
	{
		fclose(fi);
		return;
	}

	char * buf = (char *) malloc(end == 0 ? 1 : (size_t) end);
	if(buf == NULL)
	{
		fclose(fi);
		return;
	}

	size_t bytes = fread(buf, 1, (size_t) end, fi);
	fclose(fi);

	if(bytes != static_cast<size_t>(end))
	{
		free(buf);
		return;
	}

	m_buffer = buf;
	m_size   = bytes;				// nur der wirklich gelesene Teil
}

#endif

module_script_kind module::classify_script(const char * script_path)
{
	if(script_path == NULL)
		return module_script_kind::xtlua;

#if IBM
	FILE * script = _wfopen(utf8_decode(script_path).c_str(), L"rb");
#else
	FILE * script = fopen(script_path, "rb");
#endif
	if(script == NULL)
		return module_script_kind::xtlua;

	char first_line[64] = {};
	const bool read_line = fgets(first_line, sizeof(first_line), script) != NULL;
	fclose(script);
	if(!read_line)
		return module_script_kind::xtlua;

	size_t length = strlen(first_line);
	while(length > 0 &&
		(first_line[length - 1] == '\r' || first_line[length - 1] == '\n'))
	{
		first_line[--length] = 0;
	}
	if(strcmp(first_line, "--[[ XLua 2.0 ]]") == 0)
		return module_script_kind::xlua2;

	// Der lokale Kompatibilitaetsvertrag waehlt XLua 2 nur mit dem exakten
	// Marker oben. Andere XLua-Versionsmarker werden trotzdem erkannt, damit ein
	// 2.x-/zukuenftiges XLua-Skript niemals stillschweigend als xtlua_worker
	// gestartet wird.
	static const std::regex version_marker(
		R"(^--\[\[\s*XLua\s+((?:\d+\.?){1,3})\s*\]\])");
	std::cmatch match;
	if(std::regex_search(first_line, match, version_marker))
	{
		const long major = strtol(match[1].str().c_str(), NULL, 10);
		return major >= 2 ? module_script_kind::unsupported_xlua :
			module_script_kind::xtlua;
	}

	const string marker_text(first_line);
	if(marker_text.rfind("--[[", 0) == 0 &&
		marker_text.find("XLua") != string::npos)
	{
		return module_script_kind::unsupported_xlua;
	}
	return module_script_kind::xtlua;
}
